version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # добавьте здесь переменные окружения или подключите файл env
      # - TELEGRAM_BOT_TOKEN=xxx
    restart: unless-stopped
